### ISSUE TITLE
mail

### ISSUE THREAD

**Issue by efiku** [C0deboy/jaki-jezyk-programowania#1]
Kilka uwag.
emailform.php do całkowitego przepisania.

1.  $useremail  =  $_POST['mail'] ??  false; przykładowo (bo jak widać, można sobie generować błędy)
2. htmlentities jest średnie ;d z pomocą przyjdą wam filtry.
3. maile z mail() praktycznie zawsze trafiają do spamu. Od wysyłania maili jest SwiftMailer.
4.  ten if z response mógłby wyglądać ładniej.. z tego co widzę, to nie trzeba pisać cały czas die(). Używacie tam czasem PHPStorma? ;-)
5. Secret key w repo? :O

**Comment by C0deboy** [comment]
To jest secret key do local hosta, nie do naszej domeny. Co do SwiftMailera spróbujemy to ;) O dziwo sprawdzaliśmy wysyłanie maili i nie trafiały do spamu, ale jeśli jest lepsze rozwiązanie to czemu nie!

**Comment by efiku** [comment]
Wiesz, nie ważne do czego, nie powinno się znajdować w repo. (Tak na przyszłość)
Niektóre nie trafiają, a niektóre tak, ale generalnie SwiftMailer pozwoli wam w przyszłości też na jakieś grubsze zabawy z mailami ;) po prostu funkcja mail() jest stanowczo odradzana.


Kiedyś pewnie padnie pytanie, czy w ogóle potrzebujecie PHP'a :D

**Comment by C0deboy** [comment]
Przepisałem to na swiftmailera. Zobacz jak to wygląda w wolnej chwili.
1. Mówiłeś, że można posłać puste maile i, że nie sprawdzałem danych. Jednak przecież od początku były ify, które to sprawdzały. Niemniej jednak, dodałem ?? false, just in case.
2. Dane od usera lecą już przez filtr sanitize string.
3.  Już.
4. If z response, nieco skrócony ;)

Daj znać czy jest już w miarę, czy jeszcze coś trzeba poprawić.

**Comment by efiku** [comment]
Nie mam czasu za bardzo na wgryzanie się tam, ale powinno być ok.
