### ISSUE TITLE
Błąd w przykładowym kodzie C

### ISSUE THREAD

**Issue by MadRussianHacker** [C0deboy/jaki-jezyk-programowania#3]
W przykładowym kodzie języka C na stronie startowej znajduję się błąd. Otóż dyrektywa include jest pozostawiona na początku bez niczego. Powinna ona dołączać plik <stdio.h>. Czyli powinno to wyglądać tak:
`#include <stdio.h>`

Pozdrawiam!

**Comment by C0deboy** [comment]
No tak, nie escapeowałem znaków <> ;) Dzięki!
